---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create storage for dev-ssl
  file: path='{{ item }}' state=directory
  with_items:
    - '{{ dev_ssl_base_dir }}'
    - '{{ dev_ssl_base_dir }}/certs'
    - '{{ dev_ssl_base_dir }}/private'

- name: Create temp openssl config file
  shell: cp "{{ openssl_config_path }}" "/tmp/dev-openssl.conf"

- name: Add additional options to temp openssl config file
  blockinfile:
    path: /tmp/dev-openssl.conf
    block: |
      [SAN]
      subjectAltName=DNS:{{ dev_ssl_domains | join(",DNS:") }}

- name: Create private key and self-signed certificate
  shell: |
    openssl req \
           -newkey rsa:2048 \
           -nodes \
           -x509 \
           -days 3650 \
           -config /tmp/dev-openssl.conf \
           -subj "/C=XX/ST=Dev/L=The Internet/O=Acme Ltd/OU=Development/CN={{ dev_ssl_domains[0] }}/emailAddress={{ dev_ssl_email }}" \
           -extensions SAN \
           -keyout {{ dev_ssl_base_dir }}/private/{{ dev_ssl_domains[0] }}.key \
           -out {{ dev_ssl_base_dir }}/certs/{{ dev_ssl_domains[0] }}.pem
    exit 0
