---

- name: Create storage for dev-ssl
  file: path='{{ item }}' state=directory
  with_items:
    - '{{ dev_ssl_base_dir }}'
    - '{{ dev_ssl_base_dir }}/certs'
    - '{{ dev_ssl_base_dir }}/private'

- name: Create private key and self-signed certificate
  shell: openssl req \
            -newkey rsa:2048 \
            -nodes
            -keyout {{ dev_ssl_base_dir }}/private/{{ item }}.key \
            -x509
            -days 3650
            -out {{ dev_ssl_base_dir }}/certs/{{ item }}.pem \
            -subj '/C=XX/ST=Dev/L=The Internet/O=Acme Ltd/OU=Development/CN={{ item }}/emailAddress={{ dev_ssl_email }}'
  with_items: '{{ dev_ssl_domains }}'
